version: '3.3'

volumes:
  postgres_data:
  static:
  media:

services:
  postgres:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: andisaev/foodgram:v1
    restart: always
    depends_on:
      - postgres
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.6
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/code/static
      - ./media:/code/media
    depends_on:
      - web
