version: '3.6'

volumes:
  postgres_data:
  static:
  media:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: andisaev/foodgram:v1
    restart: always
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.0
    volumes:
      - media:/media
      - static:/static
      - ./nginx/default.conf:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - web