# Generated by Django 2.2 on 2021-01-19 14:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='title',
        ),
        migrations.AddField(
            model_name='tag',
            name='key',
            field=models.CharField(default=datetime.datetime(2021, 1, 19, 14, 40, 42, 381808, tzinfo=utc), max_length=60, verbose_name='Ключ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='value',
            field=models.CharField(default=datetime.datetime(2021, 1, 19, 14, 40, 49, 230208, tzinfo=utc), max_length=60, verbose_name='Значение'),
            preserve_default=False,
        ),
    ]
