# Generated by Django 2.2 on 2021-02-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20210206_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=15, null=True, verbose_name='color'),
        ),
    ]
