# Generated by Django 2.2 on 2021-02-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_tag_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='breakfast',
            field=models.BooleanField(default=False, verbose_name='Завтрак'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='dinner',
            field=models.BooleanField(default=False, verbose_name='Ужин'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='lunch',
            field=models.BooleanField(default=False, verbose_name='Обед'),
        ),
    ]
