# Generated by Django 2.2 on 2021-02-08 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20210208_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='breakfast',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='dinner',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='lunch',
        ),
    ]
