# Generated by Django 2.2 on 2021-03-08 20:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_auto_20210225_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='recipes.Quantity', to='recipes.Ingredient', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ингредиенты'),
        ),
    ]
