# Generated by Django 2.2 on 2021-03-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_auto_20210308_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='recipes.Quantity', to='recipes.Ingredient', verbose_name='Ингредиенты'),
        ),
    ]
