# Generated by Django 2.2 on 2021-03-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0022_auto_20210312_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
    ]
