# Generated by Django 2.2 on 2021-03-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0026_auto_20210312_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='recipes.Quantity', to='recipes.Ingredient', verbose_name='Ингредиенты'),
        ),
    ]
