# Generated by Django 2.2 on 2021-03-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0027_auto_20210312_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, through='recipes.Quantity', to='recipes.Ingredient', verbose_name='Ингредиенты'),
        ),
    ]
